PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/20f29e60e39f4201627bc65f6254a80d30dcf586

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (8b273b46aa1ed754bea92fd2c48b6879fb23e05b)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...20f29e60e39f4201627bc65f6254a80d30dcf586

20f29e60e3 (HEAD, origin/master) tools/testbuild.sh:  Remove bad line from usage help.
69a9f3b8ec boards/arm/stm32/stm32f4discovery:  Add Ethernet SPI ENC28J60 board support to STM32F4Discovery.
f4d8c184b0 tools/checkpatch.sh: make sure fail get the real return error value
a129389fe1 sim/README.txt: Update the SMP related section
406a9adfdd arch/sim: fix up_idle call the wrong pthread_yield version
e06a4226ed arch/sim: Reuse the main thread as the simulated CPU0
a87271617a arch/sim: Replace pthread mutex with atomic function for up_testset
7794dc8821 arch/sim: Set idle thread stack size to zero
bfe1d471ce sim/arch: Fix up_head.c:122:11:implicit declaration of function 'up_cpu_index'
2b5538d0e8 sched/init: Remove the duplicated tcb flag/cpu setting in nx_smp_start

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/779197c63e08a050c0ae17ab86933981d563a85d

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (8b273b46aa1ed754bea92fd2c48b6879fb23e05b)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...779197c63e08a050c0ae17ab86933981d563a85d

779197c6 (HEAD -> master, origin/master) Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m
2f4b309b gs2200m: Retry indefinately on GS2200M_IOC_ASSOC failure
e738fbed graphics/littlevgl/Makefile: update lvgl.h dependency to fix parallel build break